FROM python:3.6-alpine

COPY py/asl_workflow_engine /usr/src/asl_workflow_engine/
COPY py/setup.py /usr/src/

WORKDIR /usr/src

# update-ca-certificates generates a somewhat confusing/worrying warning:
# WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
# This is however apparently "normal" (though other Linux distros don't do this)
# https://github.com/gliderlabs/docker-alpine/issues/30
RUN apk update && apk upgrade && \
    apk add ca-certificates && update-ca-certificates && \
    mv asl_workflow_engine/config.json . && pip install -e .

RUN apk add --no-cache --update \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev

RUN pip install pytest

RUN mkdir /results/

# copy all python tests to a test directory ready to be executed.
COPY py/test/test* test/

ENTRYPOINT python -m pytest --junitxml /results/test_results.xml test/


